spring:
  application:
    name: ReservasServices
  datasource:
    url: jdbc:sqlserver://assu.database.windows.net:1433;salonesubd=dbo
    username: AliAdmin
    password: ZmXiT87S>\2("'yr
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

